# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832b827290060faabcb35121bb4066e112f023d3cfd3cb0f55095e0aefd44fa5049fdfaaf4fd70b1ba10e9acd3d1a8b94c414feab56d87a8c02863cb1cec9c20

test:
  secret_key_base: afb8c0aa6f0e6bdab5fde15f305ac618062c7857975ecbd0aeb7ba99a1d83830effecd11833b3c439281d9eba6d3222ca81f3680412b6a40af218a086369a552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
